### ISSUE TITLE
Framework Path causing errors

### ISSUE THREAD

**Issue by jobaa11** [ChristopherJohnston/HelloWorldPlugin#1]
I am having trouble getting my file to run a build. Is there a particular cpp file I should be in before trying to run the build? I keep getting the error message that the "JuceHeader.h" file is not found. I set up a .env and adding a variable in there, that didn't work. I  also made a copy of the module directory inside of my workspace directory and tried manually updating the cpp.properties json file. Let me know if you have any suggestions. Thanks!

**Comment by ChristopherJohnston** [comment]
Hey, this sounds like the JUCE_FRAMEWORKPATH environment variable wasn't found when compiling. Check your .env file and make sure you run "direnv allow" on the directory to ensure it is set when you cd into the directory.

By the .Env file reference I am assuming you're using direnv (https://direnv.net)

**Comment by jobaa11** [comment]
> Hey, this sounds like the JUCE_FRAMEWORKPATH environment variable wasn't found when compiling. Check your .env file and make sure you run "direnv allow" on the directory to ensure it is set when you cd into the directory.
> 
> By the .Env file reference I am assuming you're using direnv (https://direnv.net)

Thank you man, it worked. I was so use to dotenv files so I guess that's were I was stomped. Also realized that my workspaceFolder was cd'd one directory away so that was really the main issue, but I was able to solve both thanks to your direction. Much appreciated!

**Comment by ChristopherJohnston** [comment]
Great, glad you got it working. Enjoy!
